### ISSUE TITLE
Microtonal tunings

### ISSUE THREAD

**Issue by gexahedron** [magenta/midi-ddsp#34]
Hi! Great work! Do you plan to support microtonal tunings?

**Comment by lukewys** [comment]
Hi @gexahedron ! Currently, the note sequence input to the model does not enable microtonal tunings as data presentation. That is, the model is not "aware" of microtonal tunings. However, you could easily tune the microtonal tunings post hoc according to your needs by adjusting the fundamental frequency in the synthesis parameters (see https://github.com/magenta/midi-ddsp#advance-usage).

**Comment by lukewys** [comment]
Hi @gexahedron ! If you do not have further questions, I am closing the issue. Feel free to open a new issue for more questions later!
