### ISSUE TITLE
ImportError and AttributeError

### ISSUE THREAD

**Issue by MasayaKawamura** [magenta/midi-ddsp#35]
Hi! Very interesting work!
I’m trying to run [MIDI_DDSP_Demo.ipynb](https://github.com/magenta/midi-ddsp/blob/main/midi_ddsp/colab/MIDI_DDSP_Demo.ipynb), and I encountered some errors.
1. ```ImportError: cannot import name 'LD_RANGE'``` occurred in ```from ddsp.spectral_ops import F0_RANGE, LD_RANGE```(see [here](https://github.com/magenta/midi-ddsp/blob/main/midi_ddsp/modules/ddsp_inference.py#L22)). 
-> According to [DDSP](https://github.com/magenta/ddsp/blob/main/ddsp/spectral_ops.py#L32), I think ```'DB_RANGE'``` is correct, not ```'LD_RANGE'``` .

2. ```AttributeError: module 'ddsp.spectral_ops' has no attribute 'amplitude_to_db'``` occurred where ```ddsp.spectral_ops.amplitude_to_db``` is used (see [here](https://github.com/magenta/midi-ddsp/blob/main/midi_ddsp/modules/interpretable_conditioning.py#L31#L32)). 
-> According to [DDSP](https://github.com/magenta/ddsp/blob/main/ddsp/core.py#L248), I suppose it is ```'ddsp.core'```, not ```'ddsp.spectral_ops'```.

**Comment by lukewys** [comment]
Hi! Huge thanks for pointing it out! It is because DDSP updated its version and changed some apis. I updated the code and released the new pip package of MIDI-DDSP. The colab notebook should be able to run now. Please let me know if there are further problems. Huge thanks again!

**Comment by MasayaKawamura** [comment]
Thank you very much for the swift reply!
