### ISSUE TITLE
'ddsp.training.nn' has no attribute 'DictLayer'

### ISSUE THREAD

**Issue by Megan8821** [magenta/midi-ddsp#56]
Hi there, I am interested in this exciting project!
But I got this problem. May I ask how to solve it? Thanks!

**Comment by lukewys** [comment]
Hi! Could you give more context on this error? Perhaps it is because you installed an old version of ddsp. You could try install midi-ddsp via `pip install midi-ddsp` or `pip install ddsp==3.2.0`

**Comment by Megan8821** [comment]
oh, ya I got it! I’ve downloaded the latest version and that works great!
