### ISSUE TITLE
midi-ddsp 0.2.5 requires ddsp==3.2.0, but you have ddsp 3.4.0 which is incompatible.

### ISSUE THREAD

**Issue by Megan8821** [magenta/midi-ddsp#58]
If I downgrade the ```ddsp```, one of the module name called ```numba``` couldn't work. 
If I install it in 3.4.0, mididdsp couldn't meet the requirement

**Comment by lukewys** [comment]
Hi, you probably have existing ddsp installed. So you can try first uninstall both ddsp and midi-ddsp. Then `pip install midi-ddsp`.

**Comment by Megan8821** [comment]
Rrrrrrrrrrr, I successfully installed it. Thank you so much, I was stuck in it for like three days.
By the way, is it necessary to execute in the venv, or not?

**Comment by Megan8821** [comment]
Got it, thanks
