### ISSUE TITLE
Error when using "pip install midi-ddsp"

### ISSUE THREAD

**Issue by JuanCarlosMartinezSevilla** [magenta/midi-ddsp#60]
Hello everyone,

I'm trying to use midi-ddsp to synthesize a few .midi files. In order to achieve it, I create a virtual environment with:

python3 -m venv .venv
source .venv/bin/activate

note: python version == 3.10.6

After creating it I run: "pip install midi-ddsp" . Getting this error message:

Collecting ddsp
  Using cached ddsp-1.9.0-py2.py3-none-any.whl (200 kB)
  Using cached ddsp-1.7.1-py2.py3-none-any.whl (199 kB)
  Using cached ddsp-1.7.0-py2.py3-none-any.whl (197 kB)
  Using cached ddsp-1.6.5-py2.py3-none-any.whl (194 kB)
  Using cached ddsp-1.6.3-py2.py3-none-any.whl (194 kB)
  Using cached ddsp-1.6.2-py2.py3-none-any.whl (194 kB)
  Using cached ddsp-1.6.0-py2.py3-none-any.whl (194 kB)
  Using cached ddsp-1.4.0-py2.py3-none-any.whl (192 kB)
  Using cached ddsp-1.3.1-py2.py3-none-any.whl (192 kB)
  Using cached ddsp-1.3.0-py2.py3-none-any.whl (183 kB)
  Using cached ddsp-1.2.0-py2.py3-none-any.whl (179 kB)
  Using cached ddsp-1.1.0-py2.py3-none-any.whl (175 kB)
  Using cached ddsp-1.0.1-py2.py3-none-any.whl (170 kB)
  Using cached ddsp-1.0.0-py2.py3-none-any.whl (168 kB)
  Using cached ddsp-0.14.0-py2.py3-none-any.whl (143 kB)
  Using cached ddsp-0.13.1-py2.py3-none-any.whl (129 kB)
  Using cached ddsp-0.13.0-py2.py3-none-any.whl (129 kB)
  Using cached ddsp-0.12.0-py2.py3-none-any.whl (127 kB)
  Using cached ddsp-0.10.0-py2.py3-none-any.whl (109 kB)
  Using cached ddsp-0.9.0-py2.py3-none-any.whl (109 kB)
  Using cached ddsp-0.8.0-py2.py3-none-any.whl (108 kB)
  Using cached ddsp-0.7.0-py2.py3-none-any.whl (107 kB)
  Using cached ddsp-0.5.1-py2.py3-none-any.whl (101 kB)
  Using cached ddsp-0.5.0-py2.py3-none-any.whl (101 kB)
  Using cached ddsp-0.4.0-py2.py3-none-any.whl (97 kB)
  Using cached ddsp-0.2.4-py2.py3-none-any.whl (89 kB)
  Using cached ddsp-0.2.3-py2.py3-none-any.whl (89 kB)
  Using cached ddsp-0.2.2-py2.py3-none-any.whl (89 kB)
  Using cached ddsp-0.2.0-py2.py3-none-any.whl (88 kB)
  Using cached ddsp-0.1.0-py3-none-any.whl (88 kB)
  Using cached ddsp-0.0.10-py3-none-any.whl (88 kB)
  Using cached ddsp-0.0.9-py3-none-any.whl (86 kB)
  Using cached ddsp-0.0.8-py3-none-any.whl (86 kB)
  Using cached ddsp-0.0.7-py3-none-any.whl (85 kB)
  Using cached ddsp-0.0.6-py2.py3-none-any.whl (91 kB)
  Using cached ddsp-0.0.5-py2.py3-none-any.whl (91 kB)
  Using cached ddsp-0.0.4-py2.py3-none-any.whl (83 kB)
  Using cached ddsp-0.0.3-py2.py3-none-any.whl (81 kB)
  Using cached ddsp-0.0.1-py2.py3-none-any.whl (75 kB)
  Using cached ddsp-0.0.0-py2.py3-none-any.whl (75 kB)
INFO: pip is looking at multiple versions of midi-ddsp to determine which version is compatible with other requirements. This could take a while.
Collecting midi-ddsp
  Using cached midi_ddsp-0.1.3-py3-none-any.whl (56 kB)
  Using cached midi_ddsp-0.1.1-py3-none-any.whl (56 kB)
  Using cached midi_ddsp-0.1.0-py3-none-any.whl (53 kB)
ERROR: Cannot install midi-ddsp because these package versions have conflicting dependencies.

The conflict is caused by:
    ddsp 3.4.4 depends on tensorflow
    ddsp 3.4.3 depends on tensorflow
    ddsp 3.4.1 depends on tensorflow
    ddsp 3.4.0 depends on tensorflow
    ddsp 3.3.6 depends on tensorflow
    ddsp 3.3.4 depends on tensorflow
    ddsp 3.3.2 depends on tensorflow
    ddsp 3.3.0 depends on tensorflow
    ddsp 3.2.1 depends on tensorflow
    ddsp 3.2.0 depends on tensorflow
    ddsp 3.1.0 depends on tensorflow
    ddsp 1.9.0 depends on tensorflow
    ddsp 1.7.1 depends on tensorflow
    ddsp 1.7.0 depends on tensorflow
    ddsp 1.6.5 depends on tensorflow
    ddsp 1.6.3 depends on tensorflow
    ddsp 1.6.2 depends on tensorflow
    ddsp 1.6.0 depends on tensorflow
    ddsp 1.4.0 depends on tensorflow
    ddsp 1.3.1 depends on tensorflow
    ddsp 1.3.0 depends on tensorflow
    ddsp 1.2.0 depends on tensorflow
    ddsp 1.1.0 depends on tensorflow
    ddsp 1.0.1 depends on tensorflow
    ddsp 1.0.0 depends on tensorflow
    ddsp 0.14.0 depends on tensorflow
    ddsp 0.13.1 depends on tensorflow
    ddsp 0.13.0 depends on tensorflow
    ddsp 0.12.0 depends on tensorflow
    ddsp 0.10.0 depends on tensorflow
    ddsp 0.9.0 depends on tensorflow
    ddsp 0.8.0 depends on tensorflow
    ddsp 0.7.0 depends on tensorflow
    ddsp 0.5.1 depends on tensorflow
    ddsp 0.5.0 depends on tensorflow
    ddsp 0.4.0 depends on tensorflow
    ddsp 0.2.4 depends on tensorflow
    ddsp 0.2.3 depends on tensorflow
    ddsp 0.2.2 depends on tensorflow
    ddsp 0.2.0 depends on tensorflow
    ddsp 0.1.0 depends on tensorflow
    ddsp 0.0.10 depends on tensorflow
    ddsp 0.0.9 depends on tensorflow
    ddsp 0.0.8 depends on tensorflow
    ddsp 0.0.7 depends on tensorflow
    ddsp 0.0.6 depends on tensorflow
    ddsp 0.0.5 depends on tensorflow
    ddsp 0.0.4 depends on tensorflow
    ddsp 0.0.3 depends on tensorflow
    ddsp 0.0.1 depends on tensorflow
    ddsp 0.0.0 depends on tensorflow>=2.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: Resolution Impossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

========
I am currently working from an M1 mac so I would be pleased if you could help me reaching a solution for this problem.

Thank you in advance,
Juan Carlos

**Comment by lukewys** [comment]
Hi Juan,

The midi-ddsp cannot run on M1 Macbook. This is because of the pip package
involves Tensorflow on M1 Macbook has a problem recognizing pip
dependencies. I will add that into ReadMe file. There is nothing I can do
about this. I would suggest you wait until the Tensoflow team resolve this
issue.

Best regards,
Yusong

JuanCarlosMartinezSevilla ***@***.***> 于2022年9月21日周三 04:12写道：

**Comment by JuanCarlosMartinezSevilla** [comment]
Hi Yusong,

Thank you very much for the info, I'll try running it in other machine. Hope Tensorflow's team starts working for M1 Macs.

Best regards,
Juan Carlos
