### ISSUE TITLE
Question on the installation

### ISSUE THREAD

**Issue by tiianhk** [magenta/midi-ddsp#63]
Hi,

When I opened up a new colab notebook and tried to pip install the midi-ddsp package, it took over 40 minutes and the installation can not be completed. I didn't experience this until this week.

I've tried `pip install midi-ddsp` and `pip install git+https://github.com/magenta/midi-ddsp` and both gave me the same results.

It seemed like pip would spend a lot of time trying to find which version of etils was compatible.

**Comment by lukewys** [comment]
Hi, 

After some investigation, I found it is because some dependencies have updated their version and their dependencies, thus causing the problem. I updated the dependency requirement in setup.py.  It should be fine now. Please feel free to let me know if there are further problems.

Best,
Yusong

**Comment by tiianhk** [comment]
Hi Yusong,

Thank you for the troubleshooting, it works now.

Best,
Haokun
